# Generated by Django 2.2 on 2020-09-11 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_fav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_fav', to='books.Book')),
                ('user_fav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav', to='books.User')),
            ],
        ),
    ]
