# Generated by Django 2.2 on 2020-09-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_users_who_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users_who_like',
        ),
        migrations.AddField(
            model_name='book',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorited_books', to='books.User'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
